{% set name = "blobfile" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/christopher-hesse/blobfile/archive/v{{ version }}.tar.gz
  sha256: 0da77924def7d930045318fe602654c11888a47abb13e962cf7bf06f04cfe204

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=64
  run:
    - python >=3.8
    - pycryptodomex >=3.8
    - urllib3 >=1.25.3,<3
    - lxml >=4.9
    - filelock >=3.0

test:
  imports:
    - blobfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/christopher-hesse/blobfile
  license: Unlicense
  license_file: LICENSE
  summary: Read Google Cloud Storage, Azure Blobs, and local paths with the same interface

extra:
  recipe-maintainers:
    - BastianZim
