{% set name = "blobfile" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/christopher-hesse/blobfile/archive/v{{ version }}.tar.gz
  sha256: 685a36a7f90bde5c81b7d7f08a472c4dd63e24772b165be16a752213f8075cf5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - astor
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pycryptodomex >=3.8,<4.dev0
    - urllib3 >=1.25.3,<3
    - lxml >=4.9,<5.dev0
    - filelock >=3.0,<4.dev0

test:
  imports:
    - blobfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/christopher-hesse/blobfile
  license: Unlicense
  license_file: LICENSE
  summary: Read Google Cloud Storage, Azure Blobs, and local paths with the same interface

extra:
  recipe-maintainers:
    - BastianZim
